# Project information
site_name: AtomicEmbeddings
site_url: https://wmd-group.github.io/Atomic_Embeddings/
site_author: Anthony Onwuli

# Repository
repo_url: https://github.com/WMD-group/Atomic_Embeddings
repo_name: 'Atomic_Embeddings'
edit_uri: ""

nav:
    - Home: index.md
    - About: about.md
    - Getting Started: installation.md
    - 'Python package':
      - 'Core module': 'python_api/core.md'
      - 'Composition module': 'python_api/composition.md'
    - Tutorial: tutorials.md
    - reference.md
    - Contributing: contribution.md
    - Issue Tracker: https://github.com/WMD-group/Atomic_Embeddings/issues

# Configuration
theme:
  name: material
  custom_dir: docs/.overrides

plugins:
    - mkdocstrings
    - search
    - autorefs



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Configuration


# Customisation
extra:
  version:
    provider: mike
