site_name: AtomicEmbeddings

nav:
    - Home: index.md
    - About: about.md
    - Getting Started: installation.md
    - Python API: python_api.md
    - Tutorial: tutorials.md
    - reference.md
    - Contributing: contribution.md
    - Issue Tracker: https://github.com/WMD-group/Atomic_Embeddings/issues
theme: material
plugins:
    - mkdocstrings
    - search
    - autorefs
repo_url: https://github.com/WMD-group/Atomic_Embeddings
repo_name: 'Atomic_Embeddings'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
