# Project information
site_name: ElementEmbeddings
site_url: https://wmd-group.github.io/ElementEmbeddings/
site_author: Anthony Onwuli

# Repository
repo_url: https://github.com/WMD-group/ElementEmbeddings
repo_name: 'ElementEmbeddings'
edit_uri: ""

nav:
    - Home: index.md
    - About: about.md
    - Getting Started: installation.md
    - 'Python package':
      - 'Core module': 'python_api/core.md'
      - 'Composition module': 'python_api/composition.md'
      - 'Plotter module': 'python_api/plotter.md'
    - Tutorial: 
      - 'Simple usage': tutorials.md
      - 'Core usage (notebook)': tutorial/usage.ipynb
      - 'Composition usage (notebook)': tutorial/composition.ipynb
      - ' Ionic Speices (notebook)': tutorial/species.ipynb
    - Embedding Schemes:
      - 'Element Embeddings': 'embeddings/element.md'
      - Species Embeddings: 'embeddings/species.md'
    - Contributing: contribution.md
    - Issue Tracker: https://github.com/WMD-group/ElementEmbeddings/issues

# Configuration
theme:
  name: material
  custom_dir: docs/.overrides
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy


# Customisation
extra:
  version:
    provider: mike


plugins:
    - mkdocstrings
    - search
    - autorefs
    - mkdocs-jupyter:
        include_source: true
        execute: true
        allow_errors: false



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

# Configuration

