name: ElementEmbeddings CI

on:
  pull_request:
    branches:
      - main

jobs:

  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.0

  test:
    needs: qa
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8","3.9","3.10","3.11"]
        os: [ubuntu-latest,macos-latest,windows-latest]
    
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -e ".[dev]"
    - name: Check package versions
      run: |
        pip show -V elementembeddings
        pip show -V pytest
        pip show -V matplotlib
        

    - name: Run tests
      run: python -m pytest --mpl --mpl-baseline-path=src/elementembeddings/tests/baseline --cov=src/elementembeddings --cov-report=xml -v
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true

